# Generated by Django 4.2.6 on 2023-11-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuFeriaCL', '0002_item_quantity_available_post_status_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=123456, max_length=128),
            preserve_default=False,
        ),
    ]
